services:

  db:
    image: postgres:17
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - default
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env

  api:
    build: ./api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
    ports:
      - "${API_PORT}:80"
    volumes:
      - ./api/app:/app
    env_file:
      - .env

  mail:
    image: maildev/maildev
    restart: always
    networks:
      - default
    ports:
      - "${SMTP_PORT}:1025"
      - "${SMTP_WEB_PORT}:1080"
    environment:
      - MAILDEV_INCOMING_USER=${SMTP_USER}
      - MAILDEV_INCOMING_PASS=${SMTP_PASSWORD}

volumes:
  pgdata:
